version: '3.4'
name: mitkodo-services
services:
  tasksapi:
    image: ${DOCKER_REGISTRY-}tasksapi
    build:
      context: .
      dockerfile: TasksAPI/Dockerfile


  authenticationapi:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: AuthenticationAPI/Dockerfile


  employeeapi:
    image: ${DOCKER_REGISTRY-}employeeapi
    build:
      context: .
      dockerfile: EmployeeAPI/Dockerfile


  employeeworker:
    image: ${DOCKER_REGISTRY-}employeeworker
    build:
      context: .
      dockerfile: EmployeeWorker/Dockerfile


  taskworker:
    image: ${DOCKER_REGISTRY-}taskworker
    build:
      context: .
      dockerfile: TaskWorker/Dockerfile

