version: '3.4'
name: mitkodo-services
services:
  message:
    container_name: rabbitmq
    image: masstransit/rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia

  authDb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: authDb
    # ports: not actually needed, because the two services are on the same network
    #   - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
    volumes:
      - authDb:/var/opt/mssql

  authenticationapi:
    environment:
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AuthDb=Server=auth_sql_server2022;Database=AuthDb;Uid=SA;Password=A&VeryComplex123Password;TrustServerCertificate=True
      - MessageBroker__Host=message
    ports:
      - "5000:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - message
      # - authDb
       

  employeeapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      # - "5001:8080"
      - "5001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  tasksapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5002:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  employeeworker:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - MessageBroker__Host=rabbitmq
    env_file:
      - .env
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - message

  taskworker:
    environment:
      - DOTNET_ENVIRONMENT=Development

volumes:
  authDb:
  rabbitmq:
