version: "3.9"  # optional since v1.27.0
services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: Task_sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1434" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
  web_api:
    image: task_api
    container_name: web_api_application
    depends_on:
      - sql
    ports:
      - "7146:7146"
      - "5171:5171"
    environment:
      ASPNETCORE_HTTPS_PORTS: "7146"
      ASPNETCORE_HTTP_PORTS: "5171"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "MyCertificatePassword"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ${APPDATA}/ASP.NET/Https:/https:ro