FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["TaskWorker.csproj", "TaskWorker/"]
RUN dotnet restore "TaskWorker/TaskWorker.csproj"

COPY . TaskWorker/.
RUN dotnet publish -c Release -o /app TaskWorker/TaskWorker.csproj 

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS publish
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "TaskWorker.dll"]